[Interface]
# Key for chokmah
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = IPH3C5D6+77bCUgzyxkGH4zgRvvpU7KvX8g29zpCsV4=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# US-FREE#58
PublicKey = wP/7Xi9sTiO1XMpLXf/OUJiJc1E0PA3KyskMtGajEFA=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.202.2:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a0d:5600:24:6::10]:51820
PersistentKeepalive = 25
